INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Fruit', 1);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Milk', 2);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Vegetable', 3);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Roll', 4);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Indoor Plants', 5);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Beef', 6);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('sausage ', 7);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Chicken', 8);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Butter', 9);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Chocolate', 10);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('protein bar', 11);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Water', 12);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Yogurt', 13);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Sausage', 14);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Bread', 15);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Meat', 16);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Pork', 17);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Pastry', 18);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Beer', 19);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Berries', 20);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Coffee', 21);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Misc', 22);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Processed Meat', 23);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('chicken', 24);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cheese', 25);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Wine', 26);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Potato', 27);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Baking', 28);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('suger', 29);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('forzen meals', 30);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Fresh Herbs', 31);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Soda', 32);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Detergent', 33);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Grape', 34);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Fish', 35);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Paper', 36);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Pasta', 37);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Popcorn', 38);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Instant Meals', 39);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('beverages', 40);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('cake', 41);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('dog food', 42);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cleaner', 43);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cream', 44);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Alcoholic Beverages', 45);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Alcoholic Appetizers', 46);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Candy', 47);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Vegetables', 48);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Hair Care', 49);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Accessories', 50);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('eggs', 51);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('bags', 52);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('salt', 53);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('cooking oil', 54);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('baking', 55);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Snack', 56);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('pet care', 57);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Feminine Care', 58);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Storage - Organization', 59);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Soap', 60);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Household Care', 61);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('frozen dessert', 62);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Nuts', 63);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Hygiene', 64);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('sweeterns', 65);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('tools', 66);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('candy', 67);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Kitchenware', 68);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('cat food', 69);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('biscuits', 70);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('baby care', 71);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('seasonings', 72);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('paper ', 73);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('waffles', 74);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Sauces', 75);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('packed bakery', 76);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Spreads', 77);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('canned', 78);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('sauces', 79);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('oral care', 80);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Towel', 81);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('garden', 82);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cereal', 83);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('serverware', 84);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('male care', 85);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('candle', 86);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Holiday Decorations', 87);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('skin care', 88);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('first aid', 89);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('soft drinks', 90);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cleaning Products', 91);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Organic Foods', 92);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Cake', 93);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('seeds', 94);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Rice', 95);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Tea', 96);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('Salad', 97);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('soup', 98);
INSERT INTO subcategories_dim (subcategory, subcategory_id) VALUES ('canning', 99);