INSERT INTO categories_dim (category, category_id) VALUES ('Fruit', 1);
INSERT INTO categories_dim (category, category_id) VALUES ('Dairy', 2);
INSERT INTO categories_dim (category, category_id) VALUES ('Vegetables', 3);
INSERT INTO categories_dim (category, category_id) VALUES ('Bakery', 4);
INSERT INTO categories_dim (category, category_id) VALUES ('Home', 5);
INSERT INTO categories_dim (category, category_id) VALUES ('Meat', 6);
INSERT INTO categories_dim (category, category_id) VALUES ('Snacks', 7);
INSERT INTO categories_dim (category, category_id) VALUES ('Beverages', 8);
INSERT INTO categories_dim (category, category_id) VALUES ('Other', 9);
INSERT INTO categories_dim (category, category_id) VALUES ('meat', 10);
INSERT INTO categories_dim (category, category_id) VALUES ('Grains', 11);
INSERT INTO categories_dim (category, category_id) VALUES ('Pantry Staples', 12);
INSERT INTO categories_dim (category, category_id) VALUES ('frozen food', 13);
INSERT INTO categories_dim (category, category_id) VALUES ('Fresh Produce', 14);
INSERT INTO categories_dim (category, category_id) VALUES ('Household', 15);
INSERT INTO categories_dim (category, category_id) VALUES ('Prepared Foods', 16);
INSERT INTO categories_dim (category, category_id) VALUES ('beverages', 17);
INSERT INTO categories_dim (category, category_id) VALUES ('dessert', 18);
INSERT INTO categories_dim (category, category_id) VALUES ('Pet Care', 19);
INSERT INTO categories_dim (category, category_id) VALUES ('Appetizers', 20);
INSERT INTO categories_dim (category, category_id) VALUES ('Health & Beauty', 21);
INSERT INTO categories_dim (category, category_id) VALUES ('Photography', 22);
INSERT INTO categories_dim (category, category_id) VALUES ('eggs', 23);
INSERT INTO categories_dim (category, category_id) VALUES ('Household Essentials', 24);
INSERT INTO categories_dim (category, category_id) VALUES ('grocry', 25);
INSERT INTO categories_dim (category, category_id) VALUES ('graden', 26);
INSERT INTO categories_dim (category, category_id) VALUES ('Seasonal & Holiday Items', 27);
INSERT INTO categories_dim (category, category_id) VALUES ('Garden', 28);