INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('tropical fruit', 1, 1.2, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pip fruit', 3, 2.79, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('citrus fruit', 7, 1.85, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('fruit/vegetable juice', 12, 1.69, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('packaged fruit/vegetables', 13, 1.63, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('canned fruit', 109, 1.23, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen fruits', 110, 1.59, 1, 1);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('berries', 26, 2.68, 1, 20);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('grapes', 40, 2.79, 1, 34);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('whole milk', 2, 1.7, 2, 2);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('butter milk', 16, 2.79, 2, 2);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('condensed milk', 54, 2.04, 2, 2);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('UHT-milk', 64, 2.71, 2, 2);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('butter', 11, 2.79, 2, 9);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('margarine', 70, 1.96, 2, 9);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('yogurt', 18, 2.8, 2, 13);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('curd', 45, 2.19, 2, 13);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('curd cheese', 31, 1.99, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('processed cheese', 41, 2.47, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('hard cheese', 59, 3.79, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cream cheese ', 60, 2.9, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sliced cheese', 76, 1.93, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('specialty cheese', 79, 2.34, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('spread cheese', 89, 2.33, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('soft cheese', 128, 3.68, 2, 25);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('ice cream', 58, 2.49, 2, 44);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('whipped/sour cream', 74, 2.32, 2, 44);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cream', 147, 1.89, 2, 44);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('other vegetables', 4, 2.01, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('root vegetables', 22, 2.27, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pickled vegetables', 62, 1.21, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen vegetables', 75, 2.26, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('canned vegetables', 99, 1.47, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('specialty vegetables', 162, 2.02, 3, 3);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen potato products', 33, 2.66, 3, 27);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('potato products', 94, 2.98, 3, 27);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('onions', 66, 1.26, 3, 48);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('salad dressing', 161, 1.65, 3, 97);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('rolls/buns', 5, 1.52, 4, 4);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('roll products ', 131, 2.64, 4, 4);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('brown bread', 20, 2.82, 4, 15);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('white bread', 83, 1.9, 4, 15);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('semi-finished bread', 103, 1.71, 4, 15);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pastry', 24, 1.57, 4, 18);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('zwieback', 108, 1.65, 4, 70);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('long life bakery product', 119, 2.71, 4, 76);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cake bar', 154, 2.41, 4, 93);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pot plants', 6, 2.01, 5, 5);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('beef', 8, 5.23, 6, 6);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frankfurter', 9, 2.26, 6, 7);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('chicken', 10, 5.36, 6, 8);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen chicken', 87, 3.43, 6, 8);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sausage', 19, 4.7, 6, 14);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('organic sausage', 127, 3.99, 6, 14);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('hamburger meat', 21, 3.14, 6, 16);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('meat', 57, 3.13, 6, 16);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('meat spreads', 135, 3.41, 6, 16);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pork', 23, 7.36, 6, 17);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('ham', 29, 1.98, 6, 23);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('liver loaf', 107, 1.89, 10, 23);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('fish', 42, 2.57, 6, 35);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen fish', 95, 2.75, 6, 35);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('canned fish', 101, 1.29, 6, 35);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('chocolate', 14, 0.84, 7, 10);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('specialty chocolate', 53, 2.41, 7, 10);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('chocolate marshmallow', 118, 1.1, 7, 10);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cooking chocolate', 141, 1.36, 7, 10);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('specialty bar', 15, 1.08, 7, 11);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('popcorn', 47, 1.03, 7, 38);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('candy', 65, 1.18, 7, 47);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('salty snack', 80, 1.97, 7, 56);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('snack products', 126, 1.44, 7, 56);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('tidbits', 140, 1.49, 7, 56);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('nut snack', 150, 0.88, 7, 56);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('nuts/prunes', 93, 1.12, 7, 63);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('chewing gum', 100, 2.17, 7, 67);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('bottled water', 17, 2.28, 8, 12);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('canned beer', 25, 1.84, 8, 19);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('bottled beer', 50, 3.3, 8, 19);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('coffee', 27, 2.95, 8, 21);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('instant coffee', 125, 2.56, 8, 21);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('red/blush wine', 32, 2.29, 8, 26);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sparkling wine', 43, 1.04, 8, 26);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('white wine', 56, 4.3, 8, 26);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('soda', 38, 3.25, 8, 32);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('liquor', 61, 2.42, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('prosecco', 106, 2.91, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('brandy', 111, 1.22, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('rum', 117, 2.77, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('whisky', 139, 1.61, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('liqueur', 143, 2.73, 8, 45);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cocoa drinks', 151, 2.71, 8, 90);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('tea', 160, 1.24, 8, 96);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('misc. beverages', 28, 1.57, 9, 22);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('turkey', 30, 2.69, 10, 24);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('flour', 34, 2.58, 11, 28);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pasta', 46, 2.55, 11, 37);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('baking powder', 78, 2.09, 11, 55);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pudding powder', 163, 1.34, 12, 55);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cereals', 134, 2.1, 11, 83);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('rice', 159, 2.54, 11, 95);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sugar', 35, 2.68, 12, 29);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('salt', 72, 2.55, 12, 53);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('oil', 73, 2.18, 12, 54);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('specialty fat', 124, 2.86, 12, 54);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('vinegar', 92, 2.93, 25, 54);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('artif. sweetener', 97, 2.46, 12, 65);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('spices', 113, 1.68, 12, 72);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('soups', 122, 1.25, 12, 78);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('preservation products', 167, 2.53, 12, 99);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen meals', 36, 1.62, 13, 30);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('frozen dessert', 91, 1.64, 13, 62);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('waffles', 115, 2.38, 13, 74);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('herbs', 37, 1.87, 14, 31);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('detergent', 39, 2.26, 15, 33);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('newspapers', 44, 5.48, 15, 36);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cleaner', 55, 3.61, 15, 43);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('dish cleaner', 77, 4.6, 15, 43);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('bathroom cleaner', 105, 5.35, 15, 43);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('abrasive cleaner', 144, 2.39, 15, 43);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('toilet cleaner', 166, 5.0, 15, 43);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('soap', 86, 3.15, 15, 60);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('hygiene articles', 96, 4.6, 15, 64);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('kitchen towels', 132, 2.77, 15, 81);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('finished products', 48, 2.3, 16, 39);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('Instant food products', 81, 1.39, 16, 39);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('ready soups', 164, 1.26, 16, 98);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('beverages', 49, 2.81, 17, 40);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('dessert', 51, 1.16, 18, 41);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('dog food', 52, 2.2, 19, 42);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('pet care', 82, 2.66, 19, 57);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cat food', 104, 1.29, 19, 69);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('liquor (appetizer)', 63, 1.57, 20, 46);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('hair spray', 67, 2.69, 21, 49);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('female sanitary products', 84, 1.92, 21, 58);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('make up remover', 165, 2.95, 21, 58);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('baby cosmetics', 112, 2.4, 21, 71);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('dental care', 130, 1.4, 21, 80);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('male cosmetics', 137, 2.87, 21, 85);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('skin care', 148, 1.22, 21, 88);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('rubbing alcohol', 149, 1.37, 21, 89);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('photo/film', 68, 1.42, 22, 50);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('domestic eggs', 69, 1.61, 23, 51);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('shopping bags', 71, 2.51, 24, 52);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cling film/bags', 85, 1.74, 24, 59);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('house keeping products', 88, 1.16, 24, 59);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('bags', 120, 1.72, 24, 59);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('decalcifier', 90, 1.97, 24, 61);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('light bulbs', 98, 2.95, 24, 66);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('cookware', 102, 2.87, 24, 68);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('kitchen utensil', 157, 2.65, 24, 68);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('napkins', 114, 2.26, 24, 73);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('dishes', 136, 2.2, 24, 84);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('candles', 138, 2.03, 24, 86);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('softener', 152, 2.48, 24, 91);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sauces', 116, 1.96, 25, 75);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('ketchup', 146, 2.29, 25, 75);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('sweet spreads', 121, 2.84, 25, 77);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('syrup', 145, 2.95, 25, 77);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('honey', 155, 1.08, 25, 77);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('jam', 156, 1.7, 25, 77);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('mustard', 123, 2.57, 25, 79);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('mayonnaise', 129, 1.64, 25, 79);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('organic products', 153, 1.54, 25, 92);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('flower soil/fertilizer', 133, 1.84, 26, 82);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('seasonal products', 142, 2.18, 27, 87);
INSERT INTO product_dim (product_name, product_id, price, category_id, subcategory_id) VALUES ('flower (seeds)', 158, 2.38, 28, 94);